name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide details about what you'd like to see added to opticloud.

  - type: textarea
    id: problem
    attributes:
      label: Problem Description
      description: What problem does this feature solve? What pain point are you experiencing?
      placeholder: |
        Describe the current limitation or problem you're facing...
        Example: "Currently, I have to run multiple commands to deploy to different environments..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: What would you like to see implemented?
      placeholder: |
        Describe your ideal solution...
        Example: "Add a --multi-target flag that allows deploying to multiple environments in one command"
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: Which area of opticloud would this feature affect?
      options:
        - Authentication & Security
        - Package Management
        - Deployment Workflow
        - Database Operations
        - Logging & Monitoring
        - Configuration & Settings
        - CLI User Experience
        - CI/CD Integration
        - Performance & Optimization
        - Other
    validations:
      required: true

  - type: textarea
    id: examples
    attributes:
      label: Usage Examples
      description: Show how this feature would be used
      placeholder: |
        Provide command examples or usage scenarios:
        
        ```bash
        # Example command
        opticloud ship ./app --targets=test1,test2,production --type=head
        
        # Expected output
        ✅ Deployed to test1
        ✅ Deployed to test2  
        ✅ Deployed to production
        ```
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: What alternatives have you considered?
      placeholder: |
        Describe any workarounds you're currently using or other solutions you've considered...
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to your workflow?
      options:
        - Critical - Blocking my work
        - High - Would significantly improve my workflow
        - Medium - Nice to have
        - Low - Minor improvement
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: Estimated Complexity
      description: How complex do you think this feature would be to implement?
      options:
        - Simple - Small change or flag addition
        - Medium - New command or significant enhancement
        - Complex - Major architectural change
        - Not sure
    validations:
      required: false

  - type: textarea
    id: use-case
    attributes:
      label: Use Case Details
      description: Describe your specific use case and how this would help
      placeholder: |
        Provide context about your workflow, team size, deployment frequency, etc.
        This helps us understand the broader impact of the feature.
    validations:
      required: false

  - type: checkboxes
    id: compatibility
    attributes:
      label: Compatibility Considerations
      description: Should this feature maintain compatibility with existing workflows?
      options:
        - label: This feature should be backward compatible
        - label: This could be a breaking change (with proper migration)
        - label: This should be opt-in/configurable
        - label: Not applicable

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, mockups, or references that would be helpful
      placeholder: |
        Links to similar features in other tools, mockups, screenshots, etc.

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have provided a clear problem description and proposed solution
          required: true
        - label: I would be willing to help test this feature when implemented
          required: false